version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=faucet_db
      - POSTGRES_USER=faucet_user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  faucet:
    build: .
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=test_key
      - FAUCET_TIMEOUT=60
      - FAUCET_PRIVATE_KEY=35eac2fa3b6fef486570467bedee60f49525ff42a691fda9e12dba9fd30b9abf
      - POSTGRES_DB=faucet_db
      - POSTGRES_USER=faucet_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/app

  celery:
    build: .
    working_dir: /app/src
    command: celery -A app worker --loglevel=info
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - SECRET_KEY=test_key
      - FAUCET_TIMEOUT=60
      - FAUCET_PRIVATE_KEY=35eac2fa3b6fef486570467bedee60f49525ff42a691fda9e12dba9fd30b9abf
      - POSTGRES_DB=faucet_db
      - POSTGRES_USER=faucet_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/app

  celery-beat:
    build: .
    working_dir: /app/src
    command: celery -A app beat --loglevel=info
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - SECRET_KEY=test_key
      - FAUCET_TIMEOUT=60
      - FAUCET_PRIVATE_KEY=35eac2fa3b6fef486570467bedee60f49525ff42a691fda9e12dba9fd30b9abf
      - POSTGRES_DB=faucet_db
      - POSTGRES_USER=faucet_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/app

volumes:
  postgres_data:
