# Generated by Django 5.1.6 on 2025-02-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faucet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionlog",
            name="success",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
